# Generated by Django 4.2 on 2023-05-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_features", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_slip", models.ImageField(default="", upload_to="images/slip")),
            ],
        ),
    ]
