# Generated by Django 4.2 on 2023-05-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_features", "0002_formimage"),
    ]

    operations = [
        migrations.RenameModel(old_name="FormImage", new_name="ImageModel",),
        migrations.RenameField(
            model_name="imagemodel", old_name="image_slip", new_name="image",
        ),
    ]
