# Generated by Django 4.2 on 2023-05-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_features", "0003_rename_formimage_imagemodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="image",
            field=models.ImageField(upload_to="images/slip"),
        ),
    ]
